### PR TITLE
Add local copy of underscore.js

### PR DESCRIPTION
**Pull request by jeroen**
The underscore.js library will no longer be included in the next version of V8, so this adds a copy in this package.

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks! Would you have time to submit a copy to CRAN?

**Comment by jeroen** [comment]
Friendly ping :) Would it be possible to do a quick cran release with this patch, so that we can release the new version of V8?

**Comment by edwindj** [comment]
Thanks for the reminder! I prrepared a new version of daff: but the CRAN
upload (https://xmpalantir.wu.ac.at/cransubmit/) seems to be offline at the
moment...

I will upload as soon as it is possible.

Best,

Edwin
Op wo 14 feb. 2024 12:04 schreef Jeroen Ooms ***@***.***>:

**Comment by jeroen** [comment]
Thanks, it seems online from here?

Op do 15 feb. 2024 08:53 schreef Edwin de Jonge ***@***.***>:

**Comment by edwindj** [comment]
Thanks, I just uploaded it!

Best,

Edwin
Op do 15 feb 2024 om 10:19 schreef Jeroen Ooms ***@***.***>:

**Comment by edwindj** [comment]
On its way to CRAN!

Best

Edwin

Op do 15 feb 2024 om 10:24 schreef Edwin de Jonge ***@***.***>:

**Pull request merged**
